version: '2'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - cache
    links:
      - "cache:cache"
  cache:
    image: redis:alpine
    ports:
      - "6379:6379"